---
title: "2019-11-20-traits-phylogeny-test"
author: "Emeline Favreau"
date: "20/11/2019"
output: html_document
---

```{r setup, include = FALSE}
# R.Version()$version.string # "R version 3.3.2 (2016-10-31)"

basic_libraries <- c("readr",
                     "tidyverse",
                     "ggplot2")
for (lib in basic_libraries) {
        if (require(package = lib, character.only = TRUE)) {
                print("Successful")
        } else {
                print("Installing")
                install.packages(lib)
                library(lib, character.only = TRUE )
        }
}

```

The aim is to import csv files containing trait information (e.g. colony size) per species, to develop a database of traits.

```{r import data, include = FALSE}


# set path, here testing with agelaia
mypath <- "/Users/emeline/Google Drive/Sumner-projects/GOTIT/0.traits_phylogeny/project-wasp-traits-database/wasp database_Liz Rowse_sept2012/Epiponnini/csv_epiponini_2/csv_agelaia"

# set genus name
genus_name <- "agelaia"

# inspired by https://stackoverflow.com/questions/5319839/read-multiple-csv-files-into-separate-data-frames

## Read files names
raw_filenames <- list.files(path    = mypath,
                            pattern = "*.csv")


## Create list of df names without special characters
clean_names <- gsub(pattern = " |-|'|&|.csv",
                    x = raw_filenames,
                    replacement = "")

# append all df names with genus
clean_names <- paste(genus_name, clean_names, sep = "_")

# create an empty list to populate resulting df
genus_df_list <- list()

### Load all files
for(i in 1:length(raw_filenames)){
  # string with file path
  filepath <- file.path(mypath, raw_filenames[i])
  
  # temporary object from reading one path at a time
  temp_file <- read.delim(filepath,
                        sep = ",")
  
  # name the dataframe with raw name
  assign(clean_names[i], temp_file) 
  
  # save it in a list
  genus_df_list[[i]] <- assign(clean_names[i], temp_file) 
    
}

# give names to each element in list
names(genus_df_list) <- clean_names


```

## Bee and Wasp Traits 


```{r compare column names, include = FALSE}
# check resulting dataframes
str(genus_df_list)

# list columns - they are not the same
for(i in genus_df_list){
  print(colnames(i))
}



```