---
title: "2019-11-20-traits-phylogeny-test"
author: "Emeline Favreau"
date: "20/11/2019"
output: html_document
---

```{r setup, include = FALSE}
# R.Version()$version.string # "R version 3.3.2 (2016-10-31)"

basic_libraries <- c("readr",
                     "tidyverse",
                     "plyr",
                     "stringr",
                     "ggplot2",
                     "viridis")

for (lib in basic_libraries) {
        if (require(package = lib, character.only = TRUE)) {
                print("Successful")
        } else {
                print("Installing")
                install.packages(lib)
                library(lib, character.only = TRUE )
        }
}

```

The aim is to import csv files containing trait information (e.g. colony size) per species, to develop a database of traits.

```{r set parameters, include = FALSE}


# set path, here testing with agelaia
mypath <- "/Users/emeline/Google Drive/Sumner-projects/GOTIT/0.traits_phylogeny/project-wasp-traits-database/wasp database_Liz Rowse_sept2012/Epiponnini/csv_epiponini_2/csv_agelaia"

# set genus name
master_genus_name <- "agelaia"

```

```{r import data, include = FALSE}
# inspired by https://stackoverflow.com/questions/5319839/read-multiple-csv-files-into-separate-data-frames

## Read files names
raw_filenames <- list.files(path    = mypath,
                            pattern = "*.csv")


## Create list of df names without special characters
clean_names <- gsub(pattern = " |-|'|&|.csv",
                    x = raw_filenames,
                    replacement = "")

# append all df names with genus
clean_names <- paste(master_genus_name, clean_names, sep = "_")

# create an empty list to populate resulting df
genus_df_list <- list()

### Load all files
for(i in 1:length(raw_filenames)){
  # string with file path
  filepath <- file.path(mypath, raw_filenames[i])
  
  # temporary object from reading one path at a time
  temp_file <- read.delim(filepath,
                        sep = ",",
                        stringsAsFactors = FALSE,
                        na.strings = c("NA", ""),
                        strip.white = FALSE)
  
  # name the dataframe with raw name
  assign(clean_names[i], temp_file) 
  
  # save it in a list
  genus_df_list[[i]] <- assign(clean_names[i], temp_file) 
    
}

# give names to each element in list
names(genus_df_list) <- clean_names


```

## Agelaia Wasp Traits 

Searching for the common traits in all dataframes

```{r compare column names, include = TRUE}
# check resulting dataframes
#str(genus_df_list)

# list columns - they are not the same
all_traits <- c()
for(i in genus_df_list){
  all_traits <- c(all_traits, colnames(i))
}

# check the 
#unique(all_traits)

# make a dataset out of the list
large_dataset <- ldply(genus_df_list, data.frame, stringsAsFactors = FALSE)

# add a genus and a species_only column
large_dataset$genus <- gsub(pattern = " .*", x = large_dataset$species, replacement = "")
large_dataset$species_only <- gsub(pattern = "^[A-z]* ", x = large_dataset$species, replacement = "") %>% 
  gsub(pattern = " .*", x = ., replacement = "")

# remove white spaces within each string (right and left sides)
large_dataset <- large_dataset %>%
  mutate_if(is.character, str_trim, side = "both")


# nest physical traits: "no_combs", "nest_structure", "nest_architecture", "nesting_location", "nest_height_m_min", "nest_height_m_max", "colony_size", "no_workers", "nest_height_m", "no_cells"

# individual physical traits: "forewing_length_mm_min", "forewing_length_mm_max", "forewing_length_mm_mean", "worker_fertility", "head_width_mm_mean", "head_width_mm_SE", "head_length_mm_mean", "head_length_mm_SD", "alitrunk_length_mm_mean", "alitrunk_length_mm_SD", "alitrunk_width_mm_mean", "alitrunk_width_mm_SD", "head_length_mm_SE", "gena_width_mm_mean", "gena_width_mm_SE", "eye_width_mm_mean", "eye_width_mm_SE", "alitrunk_length_mm_SE", "partial_forewing_length_mm_mean", "partial_forewing_length_mm_SE"

# behaviour traits: "colony_founding_strategy", "polygyny", "foraging_pattern", "worker_reproduction"

# related to the paper: "sample_c", "latitude", "longitude", "altitude_m", "location", "sample_i", "caste", "latitude_min", "latitude_max", "longitude_min", "longitude_max", "altitude_min", "altitude_max", "colony_stage", "parasitism", "interaction_type", "parasitism_type", "parasite", "parasitoidism", "interaction_type.1", "parasitoid", "nesting_site", "no_brood", "no_empty_cells", "no_combs_max", "source", "captivity",

# others: ".id", "species", "genus", "species_only" 

## _____



# create a simple heat map
# rows are species
# columns are traits: 


# behaviour traits: "colony_founding_strategy", "polygyny", "foraging_pattern", "worker_reproduction"
behaviour_traits <- c("colony_founding_strategy", "foraging_pattern", "worker_reproduction")


# list all species:
species_vec <- unique(large_dataset$species_only)

# make a result df
behaviour_df <- as.data.frame(matrix(NA, ncol = 4))

# name the dataframe
colnames(behaviour_df) <- c("genus", "species", "trait", "option")

# run through a loop to gather info for each species
for(this_species in 1:length(species_vec)){
  
  # subset one species 
  test <- subset(large_dataset, subset = species_only == species_vec[this_species])
  
  # obtain genus
  genus_name <- unique(test$genus)
  
  # assumption: typos are less frequent than the real name
  genus_name <- ifelse(length(genus_name) > 1, names(which.max(table(test$genus))), master_genus_name)
  
  # keep info for the species
  test_behaviour <- select(test, behaviour_traits, genus, species_only)

  # obtain the option for each trait
  option_trait1 <- unique(test_behaviour$colony_founding_strategy) %>% .[!is.na(.)]
  option_trait2 <- unique(test_behaviour$foraging_pattern) %>% .[!is.na(.)]
  option_trait3 <- unique(test_behaviour$worker_reproduction) %>% .[!is.na(.)]
  
  # fill if the trait has not been recorded
  option_trait1 <- ifelse(length(option_trait1) == 0, "NA", option_trait1)
  option_trait2 <- ifelse(length(option_trait2) == 0, "NA", option_trait2)
  option_trait3 <- ifelse(length(option_trait3) == 0, "NA", option_trait3)

  # gather all info into one df: genus | species | trait1 | option
  behaviour_df_set <- as.data.frame(rbind(c(genus_name, species_vec[this_species], "colony_founding_strategy", option_trait1),
                                    c(genus_name, species_vec[this_species], "foraging_pattern",         option_trait2),
                                    c(genus_name, species_vec[this_species], "worker_reproduction",      option_trait3)),
                              stringsAsFactors = FALSE)

  
  # name columns
  colnames(behaviour_df_set) <- c("genus", "species", "trait", "option")
  
  # fill in the information
  behaviour_df <- rbind(behaviour_df, behaviour_df_set)

}

# remove rows filled with NA
behaviour_df <- behaviour_df[complete.cases(behaviour_df), ]
  
  
# Heatmap 
ggplot(behaviour_df, aes(species, trait, fill = option)) +
  geom_tile() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1)) +
  scale_fill_viridis(discrete = TRUE) +
  ggtitle(master_genus_name)

```

```{r set parameters for apoica, include = FALSE}


# set path, here testing with apoica
mypath <- "/Users/emeline/Google Drive/Sumner-projects/GOTIT/0.traits_phylogeny/project-wasp-traits-database/wasp database_Liz Rowse_sept2012/Epiponnini/csv_epiponini_2/csv_apoica"

# set genus name
master_genus_name <- "apoica"

```

```{r import data for apoica, include = FALSE}
# inspired by https://stackoverflow.com/questions/5319839/read-multiple-csv-files-into-separate-data-frames

## Read files names
raw_filenames <- list.files(path    = mypath,
                            pattern = "*.csv")


## Create list of df names without special characters
clean_names <- gsub(pattern = " |-|'|&|.csv|. ",
                    x = raw_filenames,
                    replacement = "")

# append all df names with genus
clean_names <- paste(master_genus_name, clean_names, sep = "_")

# create an empty list to populate resulting df
genus_df_list <- list()

### Load all files
for(i in 1:length(raw_filenames)){
  print(i)
  # string with file path
  filepath <- file.path(mypath, raw_filenames[i])
  
  # temporary object from reading one path at a time
  temp_file <- read.delim(filepath,
                        sep = ",",
                        stringsAsFactors = FALSE,
                        na.strings = c("NA", ""),
                        strip.white = FALSE)
  
  # name the dataframe with raw name
  assign(clean_names[i], temp_file) 
  
  # save it in a list
  genus_df_list[[i]] <- assign(clean_names[i], temp_file) 
    
}

# give names to each element in list
names(genus_df_list) <- clean_names


```

## apoica Wasp Traits 

Searching for the common traits in all dataframes

```{r compare column names apoica, include = TRUE}
# check resulting dataframes
#str(genus_df_list)

# list columns - they are not the same
all_traits <- c()
for(i in genus_df_list){
  all_traits <- c(all_traits, colnames(i))
}

# check the traits
# unique(all_traits)

        

# make a dataset out of the list
large_dataset <- ldply(genus_df_list, data.frame, stringsAsFactors = FALSE)

# add a genus and a species_only column
large_dataset$genus <- gsub(pattern = " .*", x = large_dataset$species, replacement = "")
large_dataset$species_only <- gsub(pattern = "^[A-z]* ", x = large_dataset$species, replacement = "") %>% 
  gsub(pattern = " .*", x = ., replacement = "")

# remove white spaces within each string (right and left sides)
large_dataset <- large_dataset %>%
  mutate_if(is.character, str_trim, side = "both")

# assign traits to category

# nest physical traits: "no_cells", "no_workers", "nest_height_m", "no_brood", "nest_height_m_min", "nest_height_m_max", "nest_height_cm", "nesting_material" 

# individual physical traits: "head_length_mm", "head_width_mm", "eye_length_mm", "eye_width_mm_min", "eye_width_mm_max", "thorax_length_mm_mean", "thorax_length_mm_SD", "head_height_mm_mean", "head_height_mm_SD", "head_width_mm_mean", "head_width_mm_SD", "head_length_mm_mean", "head_length_mm_SD", "thorax_height_mm_mean", "thorax_height_mm_SD", "thorax_width_mm_mean", "thorax_width_mm_SD", "forewing_length_mm_mean", "forewing_length_mm_SD", "queen_worker_size_ratio", "queen_worker_dimorphism", "forewing_length_mm"

# behaviour traits: "activity_cycle", "colony_founding_strategy", "pheromone_nest_communication", "worker_fertility", "polyethism", "task_partitioning", "polygyny", "queen_policing"

# related to the paper: "source", "captivity", "location", "latitude", "longitude", "sample_i", "caste", "sample_c", "trophallaxis", "dietary_element_invertebrates", "percentage_nest_empty", "parasitism", "parasitism_type", "parasite", "altitude_m", "nesting_location", "colony_stage",  

# others: "species"                                                                                                                                   
    

## _____



# create a simple heat map
# rows are species
# columns are traits: 


# behaviour traits: "activity_cycle", "colony_founding_strategy", "pheromone_nest_communication", "worker_fertility", "polyethism", "task_partitioning", "polygyny", "queen_policing"
behaviour_traits <- c("activity_cycle", "colony_founding_strategy", "pheromone_nest_communication", "worker_fertility", "polyethism", "task_partitioning", "polygyny", "queen_policing")


# list all species:
species_vec <- unique(large_dataset$species_only)

# make a result df
behaviour_df <- as.data.frame(matrix(NA, ncol = 4))

# name the dataframe
colnames(behaviour_df) <- c("genus", "species", "trait", "option")

# run through a loop to gather info for each species
for(this_species in 1:length(species_vec)){
  
  # subset one species 
  test <- subset(large_dataset, subset = species_only == species_vec[this_species])
  
  # obtain genus
  # assumption: typos are less frequent than the real name
  genus_name <- ifelse(length(genus_name) > 1, names(which.max(table(test$genus))), genus_name)
  
  # keep info for the species
  test_behaviour <- select(test, behaviour_traits, genus, species_only)

  # obtain the option for each trait
  option_trait1 <- unique(test_behaviour$colony_founding_strategy) %>% .[!is.na(.)]
  option_trait2 <- unique(test_behaviour$foraging_pattern) %>% .[!is.na(.)]
  option_trait3 <- unique(test_behaviour$worker_reproduction) %>% .[!is.na(.)]
  
  # fill if the trait has not been recorded
  option_trait1 <- ifelse(length(option_trait1) == 0, "NA", option_trait1)
  option_trait2 <- ifelse(length(option_trait2) == 0, "NA", option_trait2)
  option_trait3 <- ifelse(length(option_trait3) == 0, "NA", option_trait3)

  # gather all info into one df: genus | species | trait1 | option
  behaviour_df_set <- as.data.frame(rbind(c(genus_name, species_vec[this_species], "colony_founding_strategy", option_trait1),
                                    c(genus_name, species_vec[this_species], "foraging_pattern",         option_trait2),
                                    c(genus_name, species_vec[this_species], "worker_reproduction",      option_trait3)),
                              stringsAsFactors = FALSE)

  
  # name columns
  colnames(behaviour_df_set) <- c("genus", "species", "trait", "option")
  
  # fill in the information
  behaviour_df <- rbind(behaviour_df, behaviour_df_set)

}

# remove rows filled with NA
behaviour_df <- behaviour_df[complete.cases(behaviour_df), ]
  
  
# Heatmap 
ggplot(behaviour_df, aes(species, trait, fill = option)) +
  geom_tile() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1)) +
  scale_fill_viridis(discrete = TRUE) +
  ggtitle(master_genus_name)

```